### ISSUE TITLE
Package name: plot2 vs. baseplot vs. tinyplot vs. ?

### ISSUE THREAD

**Issue by zeileis** [grantmcdermott/plot2#22] opened 2023-04-14 11:11 UTC
I have been wondering whether `plot2()` is the best and/or most intuitive name for the package and its main function. It's certainly "ok" but I'm not excited about it. So I wanted to ask what you think, Grant @grantmcdermott and Vincent @vincentarelbundock, maybe others have thoughts/ideas as well.

A somewhat longer but more verbose alternative might be `baseplot()`. Short alternatives would be `draw()` or `viz()`. Currently, I think I slightly prefer `baseplot()` over `plot2()`. Other opinions or better alternatives?

**Comment by vincentarelbundock** [comment] 2023-04-14 12:20
Also not sure about `plot2`. To me, it suggests that it either wants to supersede `plot()`, or that its ultimate goal is to cover the feature set of `ggplot2`. Neither of which is quite the case.

I think I like `baseplot`; matches `basetheme`. `tinyplot` would also be an option, but I think I like that less.

I don't have great original ideas for package names, sorry. Will come back if I think of one.

**Comment by grantmcdermott** [comment] 2023-04-15 00:17
Thanks for kicking this discussion off @zeileis. I agree that this is something we need to resolve before a CRAN submission.

I'm not wedded to `plot2` and your pushback is certainly shifting my priors... But allow me to play the role of defence here for a moment. In my view, `plot2` has some key arguments in its favour:

- _Simplicity_. Not only only from the user side (just add a "2"), but also from the perspective of API management. If if we decide to add support for grouped histograms, for example, then `hist2()` offers itself as the natural and consistent function call.
- _Branding_. Funny enough, I actually think the implicit linkage to `ggplot2` is a feature, not a bug. I certainly don't envisage that we will support all, or even most, of what `ggplot2` does. But there is a non-trivial set of operations that I think we could cover that are (quote unquote) easy with `ggplot2`, but finicky with base plot. I would like `plot2` to serve as a natural alternative for this set of functions&mdash;grouped plots being the exemplar&mdash;and if some reflected <name>2 "brand recognition" helps steer people our way, all the better IMO.

I had one more point that escapes me for the moment and I have to run to pick up the kids. But will leave these two for the moment. For the record, I too prefer `baseplot` among the alternatives.

(Maybe we put it to popular vote on Tiwtter/Mastodon?)

**Comment by zeileis** [comment] 2023-04-15 01:31
Thanks, Grant, interesting! Just a couple of comments:

- For densities and histograms I would prefer the formula-based interface `...(~ x, data, type = "....")` where `type` could be `"density"` or `"histogram"`.
- I find it hard to predict whether the `plot2` a la `ggplot2` branding will work well. My gut feeling is to stay away from it, though.
- Such popular votes depend very much on the framing and I'm not sure that we can easily make it informative enough without biasing anyone. But possibly I'm overthinking it. Feel free to go ahead if you want.

**Comment by vincentarelbundock** [comment] 2023-04-15 02:35
FWIW, all the views I expressed above were (extremely) weakly held. I find your arguments reasonably compelling, and in the end I don’t think it matters that much.

plot2 might be seen by people who read the alphabetical cran index.

Feels like you should think about the above for a bit and prioritize your own vibes rather than a Twitter poll.

**Comment by zeileis** [comment] 2023-04-15 08:51
+1
Definitely your call, Grat @grantmcdermott .

**Comment by grantmcdermott** [comment] 2023-04-15 19:20
Thanks both. I don't want this to be a unilateral decision, so will perhaps ask a handful other follks instead of a poll. Either way, will mull on it a bit more this weekend.

**Comment by joshuaulrich** [comment] 2023-04-24 22:48
I've independently been thinking about names for plotting functions, as part of redesigning quantmod's charting functionality. I'm leaning toward `chart()` for that, but have also considered `graph()`. Seems like the latter could be a contender here.

**Comment by eddelbuettel** [comment] 2023-07-29 23:12
`baseplot` sounds limiting to me, as in "if that is the base what buids on top of it" ?

`tinyplot` works for me because of the zero depenencies, but that may not be everybody's cup of tea (== loosers!)  :wink: 

But they key feature really is that it is a "pure" and "base only" plot() package.  So how about `pplot` as a shorthand for `pureplot`?  Or with a wink maybe `bip` for 'batteries-included-plot' as nothing else is needed?   It needs to be _short_ and _concise_ and _descriptive_.

**Comment by eddelbuettel** [comment] 2023-12-30 17:14
Bubbling this back up as there is chatter of a CRAN release come 2024.  `plot2` is really dominated by any of the alternative so pretty-please pick something ...

**Comment by friendly** [comment] 2024-01-27 01:25
`plot2()` arose as an attempt to re-design `plot()` to be more general while remaining in the framework of base R graphics. In a way, similar to the transition from the original `ggplot` to `ggplot2`.

Echoing @eddelbuettel I think it is time to release `plot2` to CRAN.

**Comment by grantmcdermott** [comment] 2024-01-27 02:30
Thanks the prompts :-)

To be clear: This is something I'm hoping to decide pretty soon, as one of the few remaining above-the-line tasks for CRAN submission. https://github.com/grantmcdermott/plot2/issues/108

**Comment by b-rodrigues** [comment] 2024-01-27 10:19
Hey all, I've discovered this package literally 10 minutes ago as I saw @vincentarelbundock tweet on it. My 2 cents, for what they're worth: I think I'd prefer tinyplot.

I think it'll make googling and discussing it easier than baseplot which could lead to quiproquos (do you mean "baseplot" or "base plot()"? It also conveys the idea of being a lightweight package very well.

**Comment by grantmcdermott** [comment] 2024-01-31 18:31
Thanks for all the suggestions and thoughtful discussion, everyone. I want to finalise this package name ASAP, so we can move ahead with CRAN submission. Here are my summary thoughts based on all the feedback so far:

IMO the package name is now a straight shot between two options: `plot2` vs `tinyplot`.

### `plot2`

**Pros**

- The "2" suffix approach provides a natural/elegant extensibility to other functions in the package, including some that I still plan to support: `par2`, `hist2`, `barplot2`, etc. It's easy to remember (mnemonic consistency) and adapt existing vanilla `plot` code to.
- Keeps the core function names short.
- No pain involved in a name switch.

**Cons**

- Poor SEO and increases the risk of false positive search outcomes in general; Bruno's point about _quiproquos_ above. Personally, I view this as the biggest con. (FWIW the problem is likely even greater for `baseplot`, which is one reason why it's dropped out of the running for me.)
- Ambiguous intention of the package from the name alone. Personally, I don't find this argument particularly compelling. But I take the point that others are worried about it.

### `tinyplot`

**Pros**

- Potentially clearer intent from the package name. I was a little unconvinced by this earlier, especially since I want to convey that the package is not just lightweight, but also powerful (i.e., _extends_ upon base `plot`). But I think there's momentum behind the "tiny" prefix now, especially with Vincent's `tinytable` etc. so that it can successfully convey both concepts simultaneously.

**Cons**

- Doesn't have quite the same obvious mnemonic consistency as `plot2`. I mean, we can use `tinyplot()`, `tinyhist()`, `tinypar()`, etc. but I have preference for keeping function names shorter if possible. OTOH we could a shorter "t" prefix instead (or as an alias): `tplot()`, `thist()`, `tpar()`. These look uglier to me and I haven't checked the risk of namespace conflicts. But it's an option. 
- Will require a fair bit of pain to change the name, both i.t.o. _pro forma_ package writing stuff and also managing public awareness (albeit much less painful if we did it later).

I plan to make a decision by the end of the week. So, last call for any additional inputs if anyone has any!

**Comment by rupertoverall** [comment] 2024-02-02 07:34
I just came across this issue and wanted to make a plea for informative package/function names. With copy/paste and autocomplete dominant, the typable length of functions is just not really a big issue these days. Readability of code is. The 'tiny...' family of names seems like a clear winner here.

[I wonder whether the package could not be called 'tiny' and the the functions retain their base forms (e.g. `tiny::plot()`). I think enough people don't use explicit namespaces that that may become confusing though.]

**Comment by zeileis** [comment] 2024-02-02 07:52
I think `tiny` would suggest something far too broad because there are already `tinytest`, `tinytable`, `tinytex`, etc. So `tiny` might convey the erroneous impression that it is a sort of meta package.

Also, using the fully-qualified names adds an unnecessary overhead if you have already imported a function in a NAMESPACE. So at least in package code the `::` should better be avoided.

**Comment by lrberge** [comment] 2024-02-02 10:21
Not strong views here but I agree with Achim that the `tiny` prefix may be too broad. `plot2` is nice. I also agree with @eddelbuettel wise words: Your choice is the right choice!

**Comment by zeileis** [comment] 2024-02-02 10:27
Just to clarify: `tinyplot` is ok. But just `tiny` with function `tiny::plot` etc. would be a bad choice. 

Regarding `plot2` vs. `tinyplot` I think that both have advantages and disadvantages and I don't have a strong preference. Whatever Grant picks will be the right choice :+1:

**Comment by friendly** [comment] 2024-02-02 18:10
Just to weigh in again here. Grant has been magnanimous in opening this to discussion, and has presented pros and cons.

I am strongly persuaded that the `tiny` attribute is not as important **semantically** as the `2`, indicating that `plot2` extends `plot` as a new generation of base-R graphics.

**Comment by grantmcdermott** [comment] 2024-02-05 23:12
Hi all. Thanks for bearing with me and providing such constructive feedback. After much thought, here is where I've landed:

I've decided to rename the package to **tinyplot**.  The main function will similarly be called `tinyplot()`, though I will also provide a "no vowels" alias `plt()` to accommodate those who would like a shorthand. I know that aliases can be tricky from a documentation standpoint, but I feel that it's worth it in this case. I also like the fact that the no vowel approach provides a consistent---one might even say "tiny"--- syntax for other plot types that we'd like to support in the future: `tinyhist()` -> `hst()`, `tinybarplot()` -> `brplt()`,  etc.

**Summarising:**

 - **plot2** package => **tinyplot** package
 - `plot2()` => `tinyplot()` / alias = `plt()`
   - Similar "tiny" prefix / no-vowel alias approach for future plot types: `tinyhist()` / alias = `hst()` etc.   
 - `par2()` => `tpar()`

**Other comments:**

- The main checkmark against continued use of **plot2** was the risk of SEO ambiguity and confusion with **ggplot2**. Of course, this was @zeileis' original point of concern. I'm just a bit slow, so took a while to come around. 
- Having weighed all the options, I've come to the conclusion that it's better to be explicit with function names rather than succinct. So that's why the "tiny" prefix carried the day. But I personally like the option of less keystrokes and was motivated to include a decent shorthand alias, even if others hadn't request it.
- Similarly, w.r.t. function names, I also liked `tplot()` and `tp()`. But having looked into it, these two have a much higher chance of causing namespace clashes with existing packages. The latter is also potentially confusing, since I need to preserve `tpar()` (replaces `par2`) for setting global parameters.

I'll try to push through the necessary changes in the codebase and repo sometime this week. This will correspond to v0.0.5 of the package, which will be one of the last dev releases before we submit to CRAN.

Thanks again for everyone's help and input!

**Closed** 2024-02-06 06:42 UTC
Labels: design

**Comment by arnejohannesholmin** [comment] 2024-02-11 21:59
Tired of the many dependencies of ggplot2 I googled "tinyplot", and it lead me to your package. I understand that you are not aiming for a complete replacement of all ggplot2 features, but I do hope that you are aiming to be the tiny alternative. Is there an ETA on the CRAN release?

**Comment by grantmcdermott** [comment] 2024-02-12 21:49
@arnejohannesholmin Tracking in [https://github.com/grantmcdermott/tinyplot/milestone/1](this milestone) Goal ETA is end of this month. (Fingers crossed.)

**Comment by grantmcdermott** [comment] 2024-06-20 17:47
PSA: The package is now on CRAN: https://cran.r-project.org/web/packages/tinyplot/index.html
